### ISSUE TITLE
RELEASED_V2_01_20171010.zip Make reconfig 给出的系统总是desktop x86

### ISSUE THREAD

**Issue by zhangmingming** [aliyun/iotkit-embedded#10]
下面这个结果应该不对吧，总是编译失败
make reconfig 结果：
SELECTED CONFIGURATION:

VENDOR :   desktop
MODEL  :   x86

**Comment by edwardyangx** [comment]
不明白你的意思, 2.01版本只支持desktop+x86这么一个平台, make reconfig选择平台的时候当然总是这一个了, 正确的编译步骤是:

```
make reconfig
make
```

所有用户都没碰到你所说的问题, 请说明为什么你认为编译失败了

**Comment by zhangmingming** [comment]
多谢你的答复，我因为C并不熟悉，看文档说是这个sdk只支持linux 和 64位，不太理解为什么编译出来是desktop + x86呢？我想把整个mqtt走通，这个sdk在linux centos 64 位编译不通过，是我哪里搞错了吗？多谢指点

**Comment by edwardyangx** [comment]
不用谢, `desktop+x86`只是一个泛指, 因为我们目前只在`Ubuntu16.04`的64位操作系统上验证过, `CentOS`等更多的发行版尚未支持, 如果不经修改, 编译`mqtt-example`只能在Ubuntu上

请安装和我们一样的开发环境, 或者等待`CentOS`版本的支持

**Comment by edwardyangx** [comment]
另外, 你也可以等我们下一个版本发布之后(预计本月)再尝试一次, 可能新版本会不再有这个问题
