### ISSUE TITLE
如何订阅查看OTA相关Topic的信息

### ISSUE THREAD

**Issue by xwdreamer** [aliyun/iotkit-embedded#102]
使用ota-mqtt-example这个示例，连接云端的时候，提示：

Publish message to topic:/ota/device/inform/a1Ry5TXw5gc/TestDeviceForDemo,QoS=1,protocolMessageId:5 
如何查看这个topic的信息。我想看上送的版本号是多少。

![image](https://user-images.githubusercontent.com/1173919/47474125-2b453180-d848-11e8-90c3-a8a246cab1e7.png)

**Comment by seblee** [comment]
看不到的，只有发送记录 没有数据记录

**Comment by xwdreamer** [comment]
> 看不到的，只有发送记录 没有数据记录

能让开发者看到吗？

**Comment by seblee** [comment]
> > 看不到的，只有发送记录 没有数据记录
> 
> 能让开发者看到吗？

不能的，平台这里没有开发者或者不开发者的区别
