### ISSUE TITLE
visual c++ 和 keil5(MDK-ARM)均无法编译通过

### ISSUE THREAD

**Issue by zhj2232006** [aliyun/iotkit-embedded#11]
visual c++ (visual studio 2013 update5)和 keil5(MDK-ARM Pro v5.23)均无法编译通过，无法跨平台移植。显示 lite-list.h 这个文件中 list_for_each_entry_safe 语法错误，(猜测这个文件居然是从linux内核代码拷贝过来的！？ )。

**Comment by edwardyangx** [comment]
是的, SDK的主要主机开发环境是GNU Make+Ubuntu16.04, 在多处文档中也说明过了, windows的版本, 可以用mingw32编译器编译, ARM的版本, 可以用armcc或者 arm-none-eabi-gcc 编译, 这些不是障碍

**Comment by zhj2232006** [comment]
keil5 也是armcc呀？现在很多MCU都用这个工具，为啥不尽量让代码兼容标准c99.。。 无语啊，发工单联系了你们技术支持，就是一两句用mingw----不是所有小型设备都要用庞大的工具链

**Comment by edwardyangx** [comment]
让代码兼容标准C99是长期要做的, 您可以使用11月底将要发布的V2.02版本, 解决了list_for_each_entry_safe()的编译问题, 手段是去掉GNU关键字typeof, 不过Keil5的支持确实要比较久以后了, 可以留下详细的平台信息, 比如STM32哪一款开发板, 使用什么操作系统等, 我们寻找用 arm-none-eabi-gcc 支持的方式
