### ISSUE TITLE
在2.2.1 gdb可以跟踪静态库里面，在2.3.0为什么无法进入了

### ISSUE THREAD

**Issue by LeeSSXX** [aliyun/iotkit-embedded#117]
如题。

**Comment by 509728263** [comment]
取消订阅，谢谢
________________________________
发件人: lishixin <notifications@github.com>
发送时间: 2018年12月27日 2:05
收件人: aliyun/iotkit-embedded
抄送: Subscribed
主题: [aliyun/iotkit-embedded] 在2.2.1 gdb可以跟踪静态库里面，在2.3.0为什么无法进入了 (#117)


如题。

―
