### ISSUE TITLE
C-SDK 移植到无操作系统的平台

### ISSUE THREAD

**Issue by zyh2591** [aliyun/iotkit-embedded#118]
mcu无操作系统 编程环境可以是KEILC IAR ECLIPSE 我应该怎么移植，发现都是基于linux的。自己添加源码，错误一大堆，头文件不兼容，求大神指导，十分困惑

**Comment by Bloodance** [comment]
可以使用3.0版本sdk移植

**Comment by edwardyangx** [comment]
适合Keil/IAR以及无OS的SDK形态是在2019/3/15发布的SDK3.0.1中才开始提供的, 之前的SDK不适用于您的场景

请看用户手册: https://code.aliyun.com/edward.yangx/public-docs/wikis/user-guide/Linkkit_User_Manual

着重看:  不使用SDK自带编译系统时的移植示例 一章
