### ISSUE TITLE
ITE_PROPERTY_GET这个事件无法触发

### ISSUE THREAD

**Issue by LeeSSXX** [aliyun/iotkit-embedded#130]
如题

**Comment by Bloodance** [comment]
这个事件暂时没有用到，云端get直接获取的是云端保存的

**Comment by LeeSSXX** [comment]
> 这个事件暂时没有用到，云端get直接获取的是云端保存的

原来如此，但希望阿里云能把文档写明白，那些功能暂时不可用的，注释一下，不然误导人
