### ISSUE TITLE
iotx_dm_internal.h:70 没有对 server 使用宏包裹

### ISSUE THREAD

**Issue by murphyzhao** [aliyun/iotkit-embedded#149]
iotx_dm_internal.h:70 没有对 server 使用宏包裹

```
#include "dm_server_adapter.h"
#include "dm_server.h"
```

**Comment by fenghr1219** [comment]
感谢您的反馈，我们会及时跟研发反馈您的建议

**Comment by fenghr1219** [comment]
@murphyzhao 最新已修复  再次感谢您对我们的支持和建议

**Comment by murphyzhao** [comment]
> @murphyzhao 最新已修复 再次感谢您对我们的支持和建议

感谢！
关联 commit 59447febf59f91dcb53bacd79c50a5ff4f617cc4
