### ISSUE TITLE
Typo in _iotx_alcs_adapter_subdev_list_destroy cause abort signal

### ISSUE THREAD

**Issue by bzd2132** [aliyun/iotkit-embedded#151]
There has typo in the function _iotx_alcs_adapter_subdev_list_destroy, when call function IOT_Linkkit_Close, application will receive abort signal.  The iotx_alcs_send_msg_t should be iotx_alcs_subdev_item_t

Please refer the picture.
![Screenshot from 2019-07-13 12-42-59](https://user-images.githubusercontent.com/2735414/61167170-0840e600-a56d-11e9-8c04-deada54b14b3.png)

**Comment by fenghr1219** [comment]
@bzd2132
Thanks for your support and feedback,
we fixed this problem at this：
https://github.com/aliyun/iotkit-embedded/commit/7ed488671f5004ba0b2ba8158069a356d8a94233
