### ISSUE TITLE
阿里云物联网套件  阿里智能2个平台有何区别

### ISSUE THREAD

**Issue by andyzhang10** [aliyun/iotkit-embedded#16]
阿里云物联网 阿里智能2个平台有何区别

**Comment by lifang870603** [comment]
您好，阿里小智都是封闭系统，云端无法对接私有云，APP无法定制自己的APP，必须使用阿里小智APP。而阿里云物联网套件是开发系统，云端可以介入私有云，APP也可以自行开发。

**Comment by huangguozhen** [comment]
@lifang870603 阿里云物联网有公版App吗？
阿里小智和阿里云物联网设备在开发上有什么区别
谢谢
