### ISSUE TITLE
这个和2016年11月分的SDK有啥差异？

### ISSUE THREAD

**Issue by ListerTheTormentor** [aliyun/iotkit-embedded#19]
使用去年的SDK设备运行好了，之前用http post消息到http://iot.zjhbzn.com/device/bindDevice.shtml 认证，获取productKey,productSecret,topic1,topic2,用aliyun_iot_mqtt_publish指定topic发布消息。现在的SDK用mqtt发布消息的话怎么指定topic name? sample里面是 "/"PRODUCT_KEY"/"DEVICE_NAME"/data"  需要把data换成我前面得到的topic1?

**Comment by lifang870603** [comment]
您好，"/"PRODUCT_KEY"/"DEVICE_NAME"/data" 是默认支持的topic，如果您需要添加特有的topic请在阿里云控制台上进行添加。具体可以参考IoT套件关于  **4. 创建可订阅可发布的Topic**  的介绍，谢谢！
