### ISSUE TITLE
远程控制设备并返回结果这种模式下不稳定，收到消息后返会报error occur when publish?

### ISSUE THREAD

**Issue by zhangmingming** [aliyun/iotkit-embedded#22]
远程控制设备并返回结果这种模式下不稳定,一开始是好的，在线一段时间后会报error occur when publish，然后查不出错误原因，RRPC无法走通，重启后就好了。请问有发现过类似情况么？另外是不是设备名deviceName格式有要求，现在使用mac地址里面包含冒号:会不会有影响？

**Comment by lifang870603** [comment]
您好，deviceName格式是没有要求，只有长度限制32.
error occur when publish这个需要查看设备端的日志才能看到具体原因。

**Comment by zhangmingming** [comment]
您好，设备端日志没有别的错误输出，现在我们去掉冒号后观察了几天目前没有再出现异常，基本可以确定是冒号导致的，只是查不到具体在那里开始出错。

**Comment by lifang870603** [comment]
非常感谢您的反馈，这个部分我们会同云端的同学再确认一下，谢谢。
那这个问题，我就先关闭，后续有问题可以继续沟通。
