### ISSUE TITLE
iotkit套件服务端还在开发维护吗

### ISSUE THREAD

**Issue by zhaojuntao** [aliyun/iotkit-embedded#29]
如题，请问iotkit套件服务端目前是否可以商用？

**Comment by vancepym** [comment]
我也很疑惑，作为一个开源项目，这么久没更新了，实在让开发者心里不踏实啊！

**Comment by zhaojuntao** [comment]
其实很想用阿里的iot平台，但是近一两年产生了多个平台，阿里小智，阿里物联网套件，还有SDS，现在看来，还是阿里智能是一个成熟的平台，另外两个貌似都夭折了

**Comment by lifang870603** [comment]
iotkit 套件一直是有在维护和迭代的。套件的迭代频率大约是一个月一次，由于内部原因，导致2017年12月的迭代取消，给大家造成困扰，深表歉意。
阿里小智和SDS 目前都已经没有迭代的计划，我们会更多的投入到阿里物联网套件上，请知悉！
