### ISSUE TITLE
建议给输出的日志加上日期和时间信息

### ISSUE THREAD

**Issue by vancepym** [aliyun/iotkit-embedded#30]
目前的日志输出都没有包含时间戳信息，当诊断问题的时候根本就无法通过输出的日志推测发生的时间。建议考虑在每条日志输出的开头添加上相应的日期和时间信息。谢谢！

**Comment by lifang870603** [comment]
我们目前的日志系统确实是没有时间戳的，预设是认为日志打印的工具，例如终端设备，会自动时间戳功能。在进行系统移植时，也可以在log对接到各个平台时把时间戳加上。
日志系统内没有时间戳的原因是为了解耦，尽量减少耦合。
