### ISSUE TITLE
如果不是使用该iotkit,直接使用mosquitto可以对接到阿里云的iot服务器吗？

### ISSUE THREAD

**Issue by lyx10101010** [aliyun/iotkit-embedded#31]
我之前已经使用mosquitto开发好了嵌入式设备，可以使用来对接到AWS Iot Hub上，但是我看了下阿里云的Iot hub，需要的加密比较独特，这是阿里云的独有加密协议吗？直接使用mosquitto可以对接到阿里云的iot服务器吗？

**Comment by lifang870603** [comment]
阿里云接入会有特殊的加密方式，具体可以参考文档：https://help.aliyun.com/document_detail/30539.html?spm=a2c4g.11186623.6.582.iWWPnU。 
如果按照文档中的加密方式加密，是可以使用其他mqtt client连接到阿里云的iot服务器的。

**Comment by wxiangcheng** [comment]
To lifang870603 hi, mosquitto是比较通用的测试端client, 针对阿里云的三元组mqtt, 你们有测试过吗？如何连接？我试下来 好像是不兼容。
