### ISSUE TITLE
请问杭州节点的SDK移植用于其他节点的吗？什么时候出MDK编译环境

### ISSUE THREAD

**Issue by haov000** [aliyun/iotkit-embedded#34]
请问杭州节点的SDK移植可以用于其他节点的吗，中间需要修改哪部分，之前移植过杭州节点，现在要使用上海节点的，发现SDK大变样了？期待出MDK或者IAR编译环境的示例，毕竟设备端使用单片机的可能性要大，单片机上不可能跑Linux，不知道官方怎么考虑的，感觉物联网这部分像换了一批人在维护似的，和之前变化太大?

**Comment by lifang870603** [comment]
支持Keil和IAR的编译已经列入到迭代计划，后续会逐渐完善。

关于节点问题，只有在5月底之前在杭州节点创建过产品，才可以继续使用杭州节点，否则新注册的都是华东2节点。杭州节点已经开始弱化技术支持。请知悉！
