### ISSUE TITLE
建议SDK在设备连接认证阶段允许上报自定义的设备属性

### ISSUE THREAD

**Issue by vancepym** [aliyun/iotkit-embedded#35]
最近在套件的管理控制台里发现了每个设备都有一个默认的设备属性(坐标)，而且还允许添加自定义属性，这个功能很有用，但是一查后发现只提供服务端API接口， 设备端SDK尚未发现支持该功能。

如果给设备SDK加上此功能允许每次设备连接时附带一些自定义的属性键值对才会更实用。
比如可以上报当前使用的GPRS/4G模块、SIM卡、运营商等相关信息。

**Comment by lifang870603** [comment]
设备端SDK已经在最新的发布版本上有这个部分的支持，后续也会有关于这个部分比较大迭代改动。

如果目前需要使用到设备属性，服务和事件等功能，可以参考服务端的topic定义，通过MQTT直接实现，但会有一定量的开发量，请知悉！
