### ISSUE TITLE
mqtt sample project failed

### ISSUE THREAD

**Issue by xiongyu0523** [aliyun/iotkit-embedded#38]
SSL/TLS handshaking fails when running mqtt sample project in linux (productkey, devicename and secret are installed correctly), see logs:

[Log.txt](https://github.com/aliyun/iotkit-embedded/files/1757116/Log.txt)

**Comment by lifang870603** [comment]
-0x0050    MBEDTLS_ERR_NET_CONN_RESET: Connection was reset by peer.
这个是tls在建联的过程就出现了fail，被云端关闭。
如果三元组是正确可用的，请问linux的版本是什么，TLS的版本是什么。这个更像是tls的问题。
谢谢！
