### ISSUE TITLE
HAL_SleepMs 作用

### ISSUE THREAD

**Issue by ustccw** [aliyun/iotkit-embedded#39]
https://github.com/aliyun/iotkit-embedded/blob/9898a2eaf739b9f62ff6d9d3c87575e1a4d1995e/sample/mqtt/mqtt-example.c#L221
请问在这里 HAL_SleepMs 延时是什么作用，可以去掉吗

**Comment by Frank-KunLi** [comment]
这个地方HAL_SleepMs只是一个简单的测试sample，可以去掉的。

**Comment by ustccw** [comment]
@Frank-KunLi 由于服务器发消息给设备时，设置了[超时机制](https://help.aliyun.com/document_detail/57166.html?spm=a2c4g.11186623.6.625.hnrbqM)
所以有客户反馈应该去除无用的延时，以便设备快速的回复服务器，避免延时。

**Comment by ustccw** [comment]
#40

**Comment by ustccw** [comment]
#https://github.com/aliyun/iotkit-embedded/issues/40

**Comment by ustccw** [comment]
#40
