### ISSUE TITLE
feedback warning

### ISSUE THREAD

**Issue by WeldonWangwang** [aliyun/iotkit-embedded#4]
Hi, 

I found there is a samll questions in the code  `/src/packages/LITE-utils/json_parser.c#L218` , 

the structure `JSON_NV` was defined with five numbers, but on the [line218](https://github.com/aliyun/iotkit-embedded/blob/5bcfa18f2fa79deaf740bb4b1ce34300a9193fc7/src/packages/LITE-utils/json_parser.c#L218), it was initlized with only four numbers as follows:
`
JSON_NV stNV = { 0, 0, 0, 0 };`

So, it was an warning when I transplant the code

I hope this feedback will be considered.

**Comment by edwardyangx** [comment]
Thanks very much for reporting this issue. I changed it to below in our internal repository and plan to publish this in next release. Please let me know if this is OK or not in your transplant

    diff --git a/src/packages/LITE-utils/json_parser.c b/src/packages/LITE-utils/json_parser.c
    index cb09af7..d58bdcb 100644
    --- a/src/packages/LITE-utils/json_parser.c
    +++ b/src/packages/LITE-utils/json_parser.c
    @@ -183,6 +183,8 @@ int json_parse_name_value(char *p_cJsonStr, int iStrLen, json_parse_cb pfnCB, vo
     int json_get_value_by_name_cb(char *p_cName, int iNameLen, char *p_cValue, int iValueLen, int iValueType,
                                   void *p_CBData)
     {
    +    JSON_NV     *p_stNameValue = (JSON_NV *)p_CBData;
    +
     #if (JSON_DEBUG == 1)
         int         i;
     
    @@ -201,8 +203,6 @@ int json_get_value_by_name_cb(char *p_cName, int iNameLen, char *p_cValue, int i
         }
     #endif
     
    -    JSON_NV     *p_stNameValue = (JSON_NV *)p_CBData;
    -
         if (!strncmp(p_cName, p_stNameValue->pN, p_stNameValue->nLen)) {
             p_stNameValue->pV = p_cValue;
             p_stNameValue->vLen = iValueLen;
    @@ -215,8 +215,9 @@ int json_get_value_by_name_cb(char *p_cName, int iNameLen, char *p_cValue, int i
     
     char *json_get_value_by_name(char *p_cJsonStr, int iStrLen, char *p_cName, int *p_iValueLen, int *p_iValueType)
     {
    -    JSON_NV     stNV = { 0, 0, 0, 0 };
    +    JSON_NV     stNV;
     
    +    memset(&stNV, 0, sizeof(stNV));
         stNV.pN = p_cName;
         stNV.nLen = strlen(p_cName);
         if (JSON_RESULT_OK == json_parse_name_value(p_cJsonStr, iStrLen, json_get_value_by_name_cb, (void *)&stNV)) {

Your feedback is highly appreciated and welcome :)
