### ISSUE TITLE
HAL_SleepMs for loop 作用

### ISSUE THREAD

**Issue by ustccw** [aliyun/iotkit-embedded#40]
https://github.com/aliyun/iotkit-embedded/blob/9898a2eaf739b9f62ff6d9d3c87575e1a4d1995e/sample/mqtt/mqtt-example.c#L269
请问这里 HAL_SleepMs 作用是什么

**Comment by ustccw** [comment]
#39

**Comment by lifang870603** [comment]
释放CPU，让其他模块可以更好的工作。
