### ISSUE TITLE
请问有没有mqtt长连接的例子？

### ISSUE THREAD

**Issue by ebaeab** [aliyun/iotkit-embedded#45]
请问有没有mqtt长连接的例子？

**Comment by lifang870603** [comment]
mqtt-example程序发送一次消息后会自动退出，可以尝试以下任意一种方式实现长期在线。
     1.执行mqtt-example时使用命令行./mqtt-example loop，设备会保持长期在线；
     2.修改demo代码，example 的代码在最后会调用IOT_MQTT_Destroy，设备最后会变成离线状态。
      如果希望设备一直处于上线状态，请去掉IOT_MQTT_Unregister 和IOT_MQTT_Destroy的部分，然后使用
          while(1)
          {
             IOT_MQTT_Yield(pclient, 200); 
             HAL_SleepMs(100);
          }

      另外，请使用自己的productKey和deviceName，因为官方sdk使用公用设备，有其他人使用会被踢掉线，一台设备信息只能同时在线一个。

**Comment by ebaeab** [comment]
@lifang870603 谢谢

**Comment by mofadeyunduo** [comment]
mqtt 长链接只能在线一个吗？如果是，多个在线的情况该怎么处理？
@lifang870603
