### ISSUE TITLE
[Auth/http] while receiving http response timeout,the socket won't be released

### ISSUE THREAD

**Issue by Elylhance** [aliyun/iotkit-embedded#5]
utils_http.c  --Ln: 369
    if (ret > 0) {
        *p_read_len = ret;
    } else if (ret == 0) {
        /* timeout */
        return FAIL_RETURN; //Return 0, the httpclient_close(client) won't be executed.
    } else if (-1 == ret) {
        log_info("Connection closed.");
        return ERROR_HTTP_CONN;
    } else {
        log_err("Connection error (recv returned %d)", ret);
        return ERROR_HTTP_CONN;

**Comment by edwardyangx** [comment]
Thanks! Your patch will be contained in next release as below:

```
diff --git a/src/utils/misc/utils_httpc.c b/src/utils/misc/utils_httpc.c
index 2a65548..9dc8ec5 100644
--- a/src/utils/misc/utils_httpc.c
+++ b/src/utils/misc/utils_httpc.c
@@ -372,7 +372,7 @@ int httpclient_recv(httpclient_t *client, char *buf, int min_len, int max_len, i
         *p_read_len = ret;
     } else if (ret == 0) {
         /* timeout */
-        return 0;
+        return FAIL_RETURN;
     } else if (-1 == ret) {
         log_info("Connection closed.");
         return ERROR_HTTP_CONN;
```
