### ISSUE TITLE
2.10版本代码没有发布吗？

### ISSUE THREAD

**Issue by slandx** [aliyun/iotkit-embedded#56]
看到官网上显示SDK在2018/03/31发布了2.10版本的release，文件名是RELEASED_V2_10_20180331.zip，但是没有下载链接，这里的代码release版本还是2.03。什么时候更新一下代码？

**Comment by zxc1021** [comment]
官网好像已经有了。可能还没来得及同步到github上

**Comment by slandx** [comment]
看到了，多谢
