### ISSUE TITLE
[MQTT][reconnect]， If redo auth failed， maybe we also should to refresh pClient->reconnect_param.reconnect_next_time

### ISSUE THREAD

**Issue by Elylhance** [aliyun/iotkit-embedded#6]
log_info("start reconnect");
    /* REDO AUTH before each reconnection */
    if (0 != pClient->mqtt_auth()) {
        log_err("redo authentication error!\n");
        //refresh pClient->reconnect_param.reconnect_next_time here?
        return -1;
    }

**Comment by edwardyangx** [comment]
That's an option, but for now we consider reconnect failure and backoff to another time only.
