### ISSUE TITLE
Ubuntu 16.04 编译报错 是什么原因，虚拟机上安装的Ubuntu

### ISSUE THREAD

**Issue by seblee** [aliyun/iotkit-embedded#63]
总是报错，完全按照readme上操作的
![2018-05-03 2](https://user-images.githubusercontent.com/28698690/39568483-fba184c4-4ef4-11e8-8727-419f584bd536.png)

**Comment by ningpeng** [comment]
一样的问题,   估计开发不是这个版本测试的
