### ISSUE TITLE
IOTX_MQTT_EVENT_PUBLISH_RECVEIVED 可否换为 IOTX_MQTT_EVENT_PUBLISH_RECEIVED?

### ISSUE THREAD

**Issue by ustccw** [aliyun/iotkit-embedded#66]
https://github.com/aliyun/iotkit-embedded/blob/e53e5f6fc59aea4fa4ab5e8b3b7f735930bb99aa/src/sdk-impl/exports/iot_export_mqtt.h#L69

如题，单词拼写可否严谨一下？

**Comment by edwardyangx** [comment]
非常感谢指正, 已修改, 下一版本发布即可看到
