### ISSUE TITLE
http模块不能正常解析带Transfer-Encoding: chunked的responese

### ISSUE THREAD

**Issue by chipengliu** [aliyun/iotkit-embedded#8]
不知道你们的http模块是否是通用模块，当回包带有Transfer-Encoding: chunked，代码中会进入判断`if (client_data->response_content_len == -1 && client_data->is_chunked == false)`，按照期望应该进入`if (client_data->is_chunked && client_data->retrieve_len <= 0)`这里才正常的吧？

**Comment by alasika** [comment]
Hi, 当回包带有Transfer-Encoding: chunked,会置位client_data->is_chunked = true，故(client_data->response_content_len == -1 && client_data->is_chunked == false)不会进入，而是进入(client_data->is_chunked && client_data->retrieve_len <= 0)继续recv，符合期望
